# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sesh < Formula
  desc "Smart terminal session manager"
  homepage "https://github.com/joshmedeski/sesh"
  version "0.8.0"
  license "MIT"

  depends_on "tmux"
  depends_on "zoxide"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/joshmedeski/sesh/releases/download/v0.8.0/sesh_Darwin_arm64.tar.gz"
      sha256 "8ced29f3c0c4b74271647f84e37a65ce55169312b372d08f4aac8e1d73a761da"

      def install
        bin.install "sesh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/joshmedeski/sesh/releases/download/v0.8.0/sesh_Darwin_x86_64.tar.gz"
      sha256 "67744a292aed80203ce383c71b3b5ca704d0be164ba1e2e16434524eaf0855fc"

      def install
        bin.install "sesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/joshmedeski/sesh/releases/download/v0.8.0/sesh_Linux_x86_64.tar.gz"
      sha256 "c7c26f5e733be0e61c375553b35e0bdc67123491f5ba502eff7f40260e045c5f"

      def install
        bin.install "sesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshmedeski/sesh/releases/download/v0.8.0/sesh_Linux_arm64.tar.gz"
      sha256 "bf734922178b7bcb939a1654d7f74141383a8f4a27b89dc6f33517c35df604df"

      def install
        bin.install "sesh"
      end
    end
  end
end
